name: Test documentation build

on:
  pull_request:
    paths:
      - '**.py'
      - '**.ipynb'
      - '**.rst'
      - '**.md'
      - 'pyproject.toml'
      - '.github/workflows/**'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v7
        with: { python-version: "3.11" }
      - run: sudo apt-get update && sudo apt-get install -y pandoc
      - run: pip install --upgrade pip && pip install -e ".[docs]"
      - run: jupyter nbconvert --to notebook --execute notebooks/demo.ipynb --output=demo-output.ipynb --output-dir=docs/source
      - run: cd docs && make clean html
